# Generated by Django 5.1.2 on 2024-11-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='loc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
