# Generated by Django 5.1.2 on 2024-11-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='registered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.providers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodvendor',
            name='registered_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='User.providers'),
            preserve_default=False,
        ),
    ]
