# Generated by Django 5.0.4 on 2024-11-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='User.hostel'),
        ),
    ]
