# Generated by Django 5.0.4 on 2024-11-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_room_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
    ]
