# Generated by Django 5.1.2 on 2024-11-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_bookingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
